### ISSUE TITLE
Api for deleting a post by bot

### ISSUE THREAD

**Issue by vahidvdn** [bot-api/telegram#7]
Hi. I'm going to build a telegram bot for my website. When I create a new post in my website, the bot will send the post to my telegram channel directly. There is some api for doing this.

But I want this functionality, when I delete a post in my site, **bot would be able to delete the post** in the channel. I searched, but found nothing. Will be such a api for doing this?

**Comment by m0sth8** [comment]
Hi. I think you can use [api.Edit](https://github.com/bot-api/telegram/blob/master/api.go#L316) with empty text: https://core.telegram.org/bots/api#editmessagetext
